### ISSUE TITLE
Feature request: Delete message if it mentions another Telegram room

### ISSUE THREAD

**Issue by backus** [lorien/daysandbox_bot#18]
A lot of spammers join our room and send a template message saying to join some other room which they @mention. Should get auto-deleted too.

Happy to take a stab at a PR if this sounds interesting.

**Comment by lorien** [comment]
Well, room mentions are handled by bot already: https://github.com/lorien/daysandbox_bot/blob/master/daysandbox_bot.py#L425

If some mention was not deleted the possible reasons are:
* high load on the bot instance, it just has not deleted the message yet
* the mention is not a room, but a username (of some person), bot does not delete person's mentions
* the user who posted the room mention has been joined the room more than 24 hours ago

**Comment by backus** [comment]
Hm darn maybe it was a user mention. Thanks for responding quickly. We're using your bot in the [Bloom](https://t.me/bloomprotocol) room and it is great. I'll probably open separate issues if I see other features that would help. Closing this for now.
