### ISSUE TITLE
Delete posts "via @MPiarBot" and over "via"

### ISSUE THREAD

**Issue by mr-tron** [lorien/daysandbox_bot#21]

**Comment by lorien** [comment]
If you are talking about link buttons. As I know, it is not possible to do via bot API. Telegram does not send update message about buttons generated by other bot.

**Comment by mr-tron** [comment]
But you can delete all messages posted via bot, as you delete all links.

**Comment by mr-tron** [comment]
No. You can`t. Message "via @somebot" doesn`t has any special marks and looks for bot as message direct from user.
