### ISSUE TITLE
Bot do not share info or has parsing issue.

### ISSUE THREAD

**Issue by Alessar** [lorien/daysandbox_bot#26]
Bot was added. Admin rights for bot was added.
So now we can see message that "bot has access to messages"

How to check that bot works? By commands.
/help
/help@daysandbox_bot
/start@daysandbox_bot
This commands was removed by bot. So looks like bot works. But bot do not share any info about himself and his configurations.

/daysandbox_get publog
/daysandbox_set safe_hours=100
/safe_hours=100
/daysandbox_get safe_hours
/stat@daysandbox_bot
That commands were not deleted by bot at all. And as result we cannot see his configurations.

**Comment by lorien** [comment]
I do not understand. What is your question again? See FAQ: https://lorien.github.io/daysandbox_bot/index.html

**Comment by Alessar** [comment]
Yet another documentation. It is cool.
Has bot any configuration?
How I can see it?
How I can change it?

**Comment by lorien** [comment]
This is described in "/help". What do you do not understand exactly?

**Comment by Alessar** [comment]
I wrote `/help` into main chat.
Since one second that message was deleted from main chat.
In recent actions I can see that `DaySandBox deleted message` and message `/help`.
And that's all.
Where is it help? Where I should find any output from bot?

**Comment by lorien** [comment]
Write it in private message to bot

**Comment by Alessar** [comment]
It is very interesting. Is it mentioned in documentation?
OK. `/help' '/start' and '/stat' commands works into personal messages with bot.

I wrote `/daysandbox_get safe_hours` into personal messages.
Bot answered that 'This command have to be called from the group'
I wrote '/daysandbox_get safe_hours` into group.
No answers... No actions...

**Comment by lorien** [comment]
I can't answer all this endless questions. Just do not use my bot.

**Comment by Alessar** [comment]
Very interesting point of view.
I will try to say to all spammers that they must not write spam messages in my chat.
