### ISSUE TITLE
Bot doesn't delete @links if message has a lot of text and smiles

### ISSUE THREAD

**Issue by MxShift** [lorien/daysandbox_bot#28]
Something like this:

Sample text.
Day after day we change life's of all our clients . And we help them to get a better life with help of god and my bot . Since we start helping our clients 15 days ago , they start getting profit at the first time since longtime ago cause we all know the situation of the market in the past months . But my bot offered a better chance to earn a daily profit and take care of th family's of each subscriber . Thank god and after that me . 
If you want to join the pogram too or get more details contact
😀😀😀😀😀😀😀😀😀😀😀😀

@testgroup

Jdjjdkdkkdkekcjdjkd djdjjdjejej ejdjj 😀

Is it because of bot's high-load and can it be fixed by running the bot on my server?

**Comment by lorien** [comment]
Regarding high load. Yep, there could be issues. Right now bot processes from 50k to 300k messages per hour. I believe I've made good improvements in stability of bot in past few weeks. So now bot behaviouor is more predictable. Yes, you can try to run your own version of bot. Be aware that source code in this repo IS DEPRECATED. Daysandbox is not open sourced anymore.

Please write further questions and thoughts to telegram group https://t.me/tgdev_en
