### ISSUE TITLE
Do not remove IP links

### ISSUE THREAD

**Issue by lorien** [lorien/daysandbox_bot#3]
IPv4 address should not be removed. It is highly unlikely that spam messages would use IP-link to address the promoted object.

**Comment by doktor24krsk** [comment]
Kalipso

**Comment by doktor24krsk** [comment]
Kalipso

**Comment by doktor24krsk** [comment]
https://user-images.githubusercontent.com/13920194/32420033-33972b24-c2b7-11e7-86e1-c003f0c0520e.jpg
