### ISSUE TITLE
Extend sandbox period

### ISSUE THREAD

**Issue by AnotherRoger** [lorien/daysandbox_bot#30]
Spammers have become wise to the 24 hour sandbox concept, so now join groups and wait for days or weeks before sending spam. It would be useful if the default sandbox period could be changed.
At this time, I'm manually limiting new group members from posting anything for 30 days.

**Comment by lorien** [comment]
Nope, default period will stay 1 day. I think it is reasonable time for most chats.
You can try my new bot @orgrobot. I think it is quite good solution to fight spam

**Comment by lorien** [comment]
I do not see how daysandbox become obsolete. Its *default* safe time is 24 hours, but you can configure it up to 1 month.

> I'm now looking for a bot which asks new members to answer some questions before allowing membership, this may be a better answer.

I am working on such a bot: @orgrobot. You can see how it works in my group: @tgdev_en

**Comment by AnotherRoger** [comment]
Somehow I missed that it can be configured for longer periods ...how did I miss that! Is it a change which has occurred in the last year?

I've joined the tgdev group and orgrobot look like just the right thing - I'll read more about it ...but, if the questions can be customised it looks good.
An option to have a group of customisable buttons to select from would be good ....in that way new members can be asked to select a button containing answers connected to what the group discusses.
Such as:
Q - 'What is the topic of discussion in this group?'
Option 1 - 'Aircraft'
Option 2 - 'Mathematics'
Option 3 - 'Architecture'
Option 4 - 'Trading Analysis'

Only one of those would be correct.
Have the button order change at random.
Option to define more than one question.

Umm ....this is probably something I should be mentioning in the TgDev group instead.

Thanks for your efforts anyway!

**Comment by lorien** [comment]
> but, if the questions can be customised it looks good.

Questions can be customized, see https://tgdev.io/bot/orgrobot
